### ISSUE TITLE
Non-semantic transitions ids of the tracenet when doing alignments 

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#54] opened 2019-02-04 18:53 UTC
This is related to #40, the identifiers used for the trace net when returned when using `PARAM_ALIGNMENT_RESULT_IS_SYNC_PROD_AWARE` (which works well btw) are simply enumerated `t1` ... `tn`. 

I wonder whether this is a good choice since the transition ids do not refer to anything that the caller of the method recognises and do not match in between traces. So t1 for the first trace may be a different activity than t1 for the second trace. Is it a requirement of the alignment that the transitions are sequentially numbered or could this be replaced by actual event activity labels (maybe with suffixes to disambiguate duplicates).

I am not sure what is best here, but simply raising this for discussion.

**Comment by Javert899** [comment] 2019-02-05 09:33
Hi,

Do you think it is really a problem? In the current version, we offer through a flag the possibility to return for each move in the alignment the transitions names and the transitions labels; knowing the transition name in a trace net may not so important because (if uncertainty is not involved) it's a sequential model

**Comment by fmannhardt** [comment] 2019-02-05 09:51
It is more an issue that it is quite surprising to see these auto-generated names in the result. When looking at the result I first thought these were identifiers in the Petri net. It is always good to design things according to the Principle of Least Surprise. 

But, I guess this can be addressed by documentation.

**Comment by s-j-v-zelst** [comment] 2019-02-08 13:00
Hi Felix,

Do I understand you correctly:
Would it be more suitable to name the transitions of the trace net of trace <a,b,b,c> to t_a_1, t_b_1, t_b_2 and t_c_1?

I think we could do something like that.

**Comment by fmannhardt** [comment] 2019-02-08 20:46
It was more that I was surprised what these t_1, ... transitions are since there was not t_1 identifier in the Petri net. So might be just a case for documentation.

**Comment by Javert899** [comment] 2019-02-20 12:41
The issue is now resolved in the 'develop' branch according to s-j-v-zeelst feedback

**Closed** 2019-02-22 12:59 UTC
